// Package emitter writes a Circuit as QIR-compliant LLVM IR text.
//
// The emitter targets QIR specification v2.0 with opaque pointers (LLVM 16+).
// It supports both the Base Profile (static circuits) and the Adaptive Profile
// (mid-circuit measurement, classical branching, and control flow).
package emitter

import (
	"fmt"
	"io"
	"strings"

	"github.com/splch/goqu/circuit/ir"
	"github.com/splch/goqu/qir"
)

// Option configures emitter behavior.
type Option func(*config)

type config struct {
	profile    *qir.Profile // nil = auto-detect
	comments   bool
	entryPoint string
}

// WithProfile overrides the auto-detected QIR profile.
func WithProfile(p qir.Profile) Option {
	return func(c *config) { c.profile = &p }
}

// WithComments includes circuit metadata and gate annotations as LLVM IR comments.
func WithComments(include bool) Option {
	return func(c *config) { c.comments = include }
}

// WithEntryPoint sets the entry point function name. Default is the circuit
// name, falling back to "main".
func WithEntryPoint(name string) Option {
	return func(c *config) { c.entryPoint = name }
}

// Emit writes a Circuit as QIR-compliant LLVM IR to w.
func Emit(c *ir.Circuit, w io.Writer, opts ...Option) error {
	cfg := &config{}
	for _, o := range opts {
		o(cfg)
	}
	e := &emitter{c: c, w: w, cfg: cfg}
	return e.emit()
}

// EmitString returns the Circuit as a QIR LLVM IR string.
func EmitString(c *ir.Circuit, opts ...Option) (string, error) {
	var sb strings.Builder
	if err := Emit(c, &sb, opts...); err != nil {
		return "", err
	}
	return sb.String(), nil
}

type emitter struct {
	c   *ir.Circuit
	w   io.Writer
	cfg *config
	err error

	profile    qir.Profile
	entryPoint string

	// Tracks which gate intrinsic declarations are needed.
	// Runtime functions (__quantum__rt__*) are NOT registered here;
	// they are emitted directly in emitDeclarations.
	declared map[string]intrinsic

	// Measurement bookkeeping.
	numResults int

	// SSA value counter for adaptive profile.
	ssaCounter int

	// Block name counter for adaptive profile.
	blockCounter int

	// Current block label for phi predecessor tracking.
	currentBlock string
}

func (e *emitter) emit() error {
	// Reject unbound symbolic parameters.
	if free := ir.FreeParameters(e.c); len(free) > 0 {
		return fmt.Errorf("qir: circuit has unbound symbolic parameters %v; call ir.Bind() first", free)
	}

	// Determine profile.
	if e.cfg.profile != nil {
		e.profile = *e.cfg.profile
	} else {
		e.profile = qir.DetectProfile(e.c)
	}

	// Determine entry point name.
	e.entryPoint = "main"
	if e.cfg.entryPoint != "" {
		e.entryPoint = e.cfg.entryPoint
	} else if e.c.Name() != "" {
		e.entryPoint = e.c.Name()
	}

	e.declared = make(map[string]intrinsic)

	// Decompose non-QIR gates.
	circ, err := decomposeToQIR(e.c)
	if err != nil {
		return fmt.Errorf("qir: %w", err)
	}

	// Count measurements to determine required_num_results.
	e.numResults = countMeasurements(circ)

	if e.profile == qir.BaseProfile {
		return e.emitBaseProfile(circ)
	}
	return e.emitAdaptiveProfile(circ)
}

// emitBaseProfile emits a QIR Base Profile program with exactly 4 basic blocks:
// entry, body, measurements, output.
func (e *emitter) emitBaseProfile(c *ir.Circuit) error {
	// Separate gate operations from measurements.
	var gateOps, measOps []ir.Operation
	for _, op := range c.Ops() {
		if op.Gate == nil && len(op.Clbits) > 0 {
			measOps = append(measOps, op)
		} else if op.Gate != nil {
			gateOps = append(gateOps, op)
		}
	}

	// Emit module header.
	if e.cfg.comments {
		e.writef("; QIR Base Profile - generated by goqu\n")
	}
	e.writef("%%Result = type opaque\n")
	e.writef("%%Qubit = type opaque\n\n")

	// Emit output label string constants.
	for i := range e.numResults {
		label := fmt.Sprintf("r%d", i)
		e.writef("@%d = internal constant [%d x i8] c\"%s\\00\"\n", i, len(label)+1, label)
	}
	if e.numResults > 0 {
		// Array label constant.
		e.writef("@%d = internal constant [7 x i8] c\"output\\00\"\n", e.numResults)
		e.writef("\n")
	}

	// Emit entry point function.
	e.writef("define i64 @%s() #0 {\n", e.entryPoint)

	// Block: entry.
	e.writef("entry:\n")
	e.writef("  call void @__quantum__rt__initialize(ptr null)\n")
	e.writef("  br label %%body\n")

	// Block: body.
	e.writef("body:\n")
	for _, op := range gateOps {
		e.emitGateCall(op)
	}
	e.writef("  br label %%measurements\n")

	// Block: measurements.
	e.writef("measurements:\n")
	for i, op := range measOps {
		qubit := op.Qubits[0]
		e.writef("  call void @__quantum__qis__mz__body(%s, %s)\n",
			qubitRef(qubit), resultRefWriteonly(i))
		e.declareFn(intrinsic{name: "__quantum__qis__mz__body", sig: sigMeasure})
	}
	e.writef("  br label %%output\n")

	// Block: output.
	e.writef("output:\n")
	if e.numResults > 0 {
		e.writef("  call void @__quantum__rt__tuple_record_output(i64 %d, ptr @%d)\n",
			e.numResults, e.numResults)
		// array_record_output is declared manually in emitDeclarations.
	}
	for i := range e.numResults {
		e.writef("  call void @__quantum__rt__result_record_output(%s, ptr @%d)\n",
			resultRef(i), i)
	}
	e.writef("  ret i64 0\n")
	e.writef("}\n\n")

	// Emit function declarations.
	e.emitDeclarations()

	// Emit attribute groups.
	e.writef("attributes #0 = { \"entry_point\" \"qir_profiles\"=\"%s\" \"output_labeling_schema\"=\"schema_id\" \"required_num_qubits\"=\"%d\" \"required_num_results\"=\"%d\" }\n",
		e.profile, c.NumQubits(), e.numResults)
	e.writef("attributes #1 = { \"irreversible\" }\n\n")

	// Emit module metadata.
	e.emitModuleFlags()

	return e.err
}

// emitAdaptiveProfile emits a QIR Adaptive Profile program with dynamic
// block structure supporting mid-circuit measurement and classical branching.
func (e *emitter) emitAdaptiveProfile(c *ir.Circuit) error {
	// Emit module header.
	if e.cfg.comments {
		e.writef("; QIR Adaptive Profile - generated by goqu\n")
	}
	e.writef("%%Result = type opaque\n")
	e.writef("%%Qubit = type opaque\n\n")

	// Emit output label string constants.
	for i := range e.numResults {
		label := fmt.Sprintf("r%d", i)
		e.writef("@%d = internal constant [%d x i8] c\"%s\\00\"\n", i, len(label)+1, label)
	}
	if e.numResults > 0 {
		e.writef("@%d = internal constant [7 x i8] c\"output\\00\"\n", e.numResults)
		e.writef("\n")
	}

	// Emit entry point function.
	e.writef("define i64 @%s() #0 {\n", e.entryPoint)
	e.writef("entry:\n")
	e.writef("  call void @__quantum__rt__initialize(ptr null)\n")
	e.writef("  br label %%body\n")
	e.currentBlock = "body"
	e.writef("body:\n")

	// Emit operations sequentially; measurements can appear inline.
	measIdx := 0
	ops := c.Ops()
	for _, op := range ops {
		if op.ControlFlow != nil {
			e.emitControlFlow(op.ControlFlow, &measIdx)
			continue
		}
		if op.Gate == nil && len(op.Clbits) > 0 {
			// Inline measurement.
			e.writef("  call void @__quantum__qis__mz__body(%s, %s)\n",
				qubitRef(op.Qubits[0]), resultRefWriteonly(measIdx))
			e.declareFn(intrinsic{name: "__quantum__qis__mz__body", sig: sigMeasure})
			measIdx++
			continue
		}
		if op.Condition != nil {
			e.emitConditionedOp(op, &measIdx)
			continue
		}
		if op.Gate != nil {
			e.emitGateCall(op)
		}
	}

	// Output block.
	e.writef("  br label %%output\n")
	e.writef("output:\n")
	if e.numResults > 0 {
		e.writef("  call void @__quantum__rt__tuple_record_output(i64 %d, ptr @%d)\n",
			e.numResults, e.numResults)
		// array_record_output is declared manually in emitDeclarations.
	}
	for i := range e.numResults {
		e.writef("  call void @__quantum__rt__result_record_output(%s, ptr @%d)\n",
			resultRef(i), i)
	}
	e.writef("  ret i64 0\n")
	e.writef("}\n\n")

	// Emit function declarations.
	e.emitDeclarations()

	// Emit attribute groups.
	e.writef("attributes #0 = { \"entry_point\" \"qir_profiles\"=\"%s\" \"output_labeling_schema\"=\"schema_id\" \"required_num_qubits\"=\"%d\" \"required_num_results\"=\"%d\" }\n",
		e.profile, c.NumQubits(), e.numResults)
	e.writef("attributes #1 = { \"irreversible\" }\n\n")

	// Emit module metadata.
	e.emitModuleFlags()

	return e.err
}

// emitGateCall emits a single gate call instruction.
func (e *emitter) emitGateCall(op ir.Operation) {
	if op.Gate == nil {
		return
	}

	name := op.Gate.Name()

	// Skip pseudo-gates and no-ops with no QIR representation.
	switch name {
	case "barrier", "delay", "I":
		return
	}

	// Handle reset.
	if name == "reset" {
		e.writef("  call void @__quantum__qis__reset__body(%s)\n", qubitRef(op.Qubits[0]))
		e.declareFn(intrinsic{name: "__quantum__qis__reset__body", sig: sigReset})
		return
	}

	intr, ok := lookupGate(name)
	if !ok {
		// Should not happen after decomposition, but emit a comment for debugging.
		e.writef("  ; WARNING: no QIR intrinsic for gate %q\n", name)
		return
	}

	e.declareFn(intr)

	params := op.Gate.Params()

	switch intr.sig {
	case sig1Q:
		comment := e.gateComment(name, op.Qubits)
		e.writef("  call void @%s(%s)%s\n", intr.name, qubitRef(op.Qubits[0]), comment)

	case sig1QParam1:
		comment := e.gateComment(name, op.Qubits)
		e.writef("  call void @%s(double %.17e, %s)%s\n",
			intr.name, params[0], qubitRef(op.Qubits[0]), comment)

	case sig2Q:
		comment := e.gateComment(name, op.Qubits)
		e.writef("  call void @%s(%s, %s)%s\n",
			intr.name, qubitRef(op.Qubits[0]), qubitRef(op.Qubits[1]), comment)

	case sig2QParam1:
		comment := e.gateComment(name, op.Qubits)
		e.writef("  call void @%s(double %.17e, %s, %s)%s\n",
			intr.name, params[0], qubitRef(op.Qubits[0]), qubitRef(op.Qubits[1]), comment)

	case sig3Q:
		comment := e.gateComment(name, op.Qubits)
		e.writef("  call void @%s(%s, %s, %s)%s\n",
			intr.name, qubitRef(op.Qubits[0]), qubitRef(op.Qubits[1]), qubitRef(op.Qubits[2]), comment)
	}
}

// emitConditionedOp emits a classically conditioned gate as a branch.
func (e *emitter) emitConditionedOp(op ir.Operation, measIdx *int) {
	// Read the measurement result.
	resultIdx := op.Condition.Clbit
	ssaVal := e.nextSSA()
	e.writef("  %%%d = call i1 @__quantum__rt__read_result(%s)\n",
		ssaVal, resultRefReadonly(resultIdx))
	// read_result is declared manually in emitDeclarations.

	thenLabel := e.nextBlock("then")
	contLabel := e.nextBlock("continue")

	// Branch on condition value.
	if op.Condition.Value == 1 {
		e.writef("  br i1 %%%d, label %%%s, label %%%s\n", ssaVal, thenLabel, contLabel)
	} else {
		e.writef("  br i1 %%%d, label %%%s, label %%%s\n", ssaVal, contLabel, thenLabel)
	}

	e.currentBlock = thenLabel
	e.writef("%s:\n", thenLabel)
	// Emit the conditioned gate(s).
	plain := ir.Operation{Gate: op.Gate, Qubits: op.Qubits, Clbits: op.Clbits}
	if op.Gate == nil && len(op.Clbits) > 0 {
		// Conditioned measurement.
		e.writef("  call void @__quantum__qis__mz__body(%s, %s)\n",
			qubitRef(op.Qubits[0]), resultRefWriteonly(*measIdx))
		e.declareFn(intrinsic{name: "__quantum__qis__mz__body", sig: sigMeasure})
		*measIdx++
	} else {
		e.emitGateCall(plain)
	}
	e.writef("  br label %%%s\n", contLabel)
	e.currentBlock = contLabel
	e.writef("%s:\n", contLabel)
}

// emitControlFlow emits structured control flow for the adaptive profile.
func (e *emitter) emitControlFlow(cf *ir.ControlFlow, measIdx *int) {
	switch cf.Type {
	case ir.ControlFlowIfElse:
		e.emitIfElse(cf, measIdx)
	case ir.ControlFlowWhile:
		e.emitWhile(cf, measIdx)
	case ir.ControlFlowFor:
		e.emitFor(cf, measIdx)
	case ir.ControlFlowSwitch:
		e.emitSwitch(cf, measIdx)
	}
}

func (e *emitter) emitIfElse(cf *ir.ControlFlow, measIdx *int) {
	resultIdx := cf.Condition.Clbit
	ssaVal := e.nextSSA()
	e.writef("  %%%d = call i1 @__quantum__rt__read_result(%s)\n",
		ssaVal, resultRefReadonly(resultIdx))
	// read_result is declared manually in emitDeclarations.

	ifLabel := e.nextBlock("if_body")
	elseLabel := e.nextBlock("else_body")
	joinLabel := e.nextBlock("if_end")

	hasElse := len(cf.Bodies) > 1 && len(cf.Bodies[1]) > 0

	if cf.Condition.Value == 1 {
		if hasElse {
			e.writef("  br i1 %%%d, label %%%s, label %%%s\n", ssaVal, ifLabel, elseLabel)
		} else {
			e.writef("  br i1 %%%d, label %%%s, label %%%s\n", ssaVal, ifLabel, joinLabel)
		}
	} else {
		if hasElse {
			e.writef("  br i1 %%%d, label %%%s, label %%%s\n", ssaVal, elseLabel, ifLabel)
		} else {
			e.writef("  br i1 %%%d, label %%%s, label %%%s\n", ssaVal, joinLabel, ifLabel)
		}
	}

	// If body.
	e.currentBlock = ifLabel
	e.writef("%s:\n", ifLabel)
	e.emitOps(cf.Bodies[0], measIdx)
	e.writef("  br label %%%s\n", joinLabel)

	// Else body.
	if hasElse {
		e.currentBlock = elseLabel
		e.writef("%s:\n", elseLabel)
		e.emitOps(cf.Bodies[1], measIdx)
		e.writef("  br label %%%s\n", joinLabel)
	}

	e.currentBlock = joinLabel
	e.writef("%s:\n", joinLabel)
}

func (e *emitter) emitWhile(cf *ir.ControlFlow, measIdx *int) {
	headerLabel := e.nextBlock("while_header")
	bodyLabel := e.nextBlock("while_body")
	exitLabel := e.nextBlock("while_exit")

	e.writef("  br label %%%s\n", headerLabel)
	e.currentBlock = headerLabel
	e.writef("%s:\n", headerLabel)

	// Read condition.
	resultIdx := cf.Condition.Clbit
	ssaVal := e.nextSSA()
	e.writef("  %%%d = call i1 @__quantum__rt__read_result(%s)\n",
		ssaVal, resultRefReadonly(resultIdx))
	// read_result is declared manually in emitDeclarations.

	if cf.Condition.Value == 1 {
		e.writef("  br i1 %%%d, label %%%s, label %%%s\n", ssaVal, bodyLabel, exitLabel)
	} else {
		e.writef("  br i1 %%%d, label %%%s, label %%%s\n", ssaVal, exitLabel, bodyLabel)
	}

	e.currentBlock = bodyLabel
	e.writef("%s:\n", bodyLabel)
	e.emitOps(cf.Bodies[0], measIdx)
	e.writef("  br label %%%s\n", headerLabel)

	e.currentBlock = exitLabel
	e.writef("%s:\n", exitLabel)
}

func (e *emitter) emitFor(cf *ir.ControlFlow, measIdx *int) {
	r := cf.ForRange
	headerLabel := e.nextBlock("for_header")
	bodyLabel := e.nextBlock("for_body")
	exitLabel := e.nextBlock("for_exit")

	// Initialize counter.
	predecessorBlock := e.currentBlock
	e.writef("  br label %%%s\n", headerLabel)
	e.currentBlock = headerLabel
	e.writef("%s:\n", headerLabel)

	phiSSA := e.nextSSA()
	incrSSA := e.nextSSA()
	cmpSSA := e.nextSSA()

	e.writef("  %%%d = phi i64 [ %d, %%%s ], [ %%%d, %%%s ]\n",
		phiSSA, r.Start, predecessorBlock, incrSSA, bodyLabel)
	e.writef("  %%%d = icmp slt i64 %%%d, %d\n", cmpSSA, phiSSA, r.End)
	e.writef("  br i1 %%%d, label %%%s, label %%%s\n", cmpSSA, bodyLabel, exitLabel)

	e.currentBlock = bodyLabel
	e.writef("%s:\n", bodyLabel)
	e.emitOps(cf.Bodies[0], measIdx)
	e.writef("  %%%d = add i64 %%%d, %d\n", incrSSA, phiSSA, r.Step)
	e.writef("  br label %%%s\n", headerLabel)

	e.currentBlock = exitLabel
	e.writef("%s:\n", exitLabel)
}

func (e *emitter) emitSwitch(cf *ir.ControlFlow, measIdx *int) {
	// Read the switch value from multiple classical bits.
	// For simplicity, read the first classical bit as an i64.
	sa := cf.SwitchArg
	resultIdx := 0
	if len(sa.Clbits) > 0 {
		resultIdx = sa.Clbits[0]
	}
	ssaVal := e.nextSSA()
	e.writef("  %%%d = call i1 @__quantum__rt__read_result(%s)\n",
		ssaVal, resultRefReadonly(resultIdx))
	// read_result is declared manually in emitDeclarations.

	// Extend to i64 for switch.
	extSSA := e.nextSSA()
	e.writef("  %%%d = zext i1 %%%d to i64\n", extSSA, ssaVal)

	exitLabel := e.nextBlock("switch_exit")
	defaultLabel := exitLabel

	// Determine default label.
	if len(cf.Bodies) > len(sa.Cases) {
		defaultLabel = e.nextBlock("switch_default")
	}

	// Build switch cases.
	var cases strings.Builder
	caseLabels := make([]string, len(sa.Cases))
	for i, val := range sa.Cases {
		label := e.nextBlock(fmt.Sprintf("case_%d", val))
		caseLabels[i] = label
		fmt.Fprintf(&cases, "\n    i64 %d, label %%%s", val, label)
	}

	e.writef("  switch i64 %%%d, label %%%s [%s\n  ]\n", extSSA, defaultLabel, cases.String())

	// Emit case bodies.
	for i, label := range caseLabels {
		if i < len(cf.Bodies) {
			e.currentBlock = label
			e.writef("%s:\n", label)
			e.emitOps(cf.Bodies[i], measIdx)
			e.writef("  br label %%%s\n", exitLabel)
		}
	}

	// Default body.
	if len(cf.Bodies) > len(sa.Cases) {
		e.currentBlock = defaultLabel
		e.writef("%s:\n", defaultLabel)
		e.emitOps(cf.Bodies[len(cf.Bodies)-1], measIdx)
		e.writef("  br label %%%s\n", exitLabel)
	}

	e.currentBlock = exitLabel
	e.writef("%s:\n", exitLabel)
}

// emitOps emits a slice of operations (used for control flow bodies).
func (e *emitter) emitOps(ops []ir.Operation, measIdx *int) {
	for _, op := range ops {
		if e.err != nil {
			return
		}
		if op.ControlFlow != nil {
			e.emitControlFlow(op.ControlFlow, measIdx)
			continue
		}
		if op.Gate == nil && len(op.Clbits) > 0 {
			e.writef("  call void @__quantum__qis__mz__body(%s, %s)\n",
				qubitRef(op.Qubits[0]), resultRefWriteonly(*measIdx))
			e.declareFn(intrinsic{name: "__quantum__qis__mz__body", sig: sigMeasure})
			*measIdx++
			continue
		}
		if op.Condition != nil {
			e.emitConditionedOp(op, measIdx)
			continue
		}
		if op.Gate != nil {
			e.emitGateCall(op)
		}
	}
}

// emitDeclarations writes the declare statements for all referenced intrinsics.
func (e *emitter) emitDeclarations() {
	// Always declare initialize.
	e.writef("declare void @__quantum__rt__initialize(ptr)\n")

	// Emit gate intrinsic declarations.
	for _, intr := range e.declared {
		e.writef("%s\n", sigDeclaration(intr))
	}

	// Emit runtime declarations as needed.
	if e.numResults > 0 {
		e.writef("declare void @__quantum__rt__tuple_record_output(i64, ptr)\n")
		e.writef("declare void @__quantum__rt__result_record_output(ptr, ptr)\n")
	}

	if e.profile == qir.AdaptiveProfile {
		e.writef("declare i1 @__quantum__rt__read_result(ptr readonly)\n")
	}

	e.writef("\n")
}

// emitModuleFlags writes the QIR module metadata.
func (e *emitter) emitModuleFlags() {
	e.writef("!llvm.module.flags = !{!0, !1, !2, !3}\n")
	e.writef("!0 = !{i32 1, !\"qir_major_version\", i32 2}\n")
	e.writef("!1 = !{i32 7, !\"qir_minor_version\", i32 0}\n")
	e.writef("!2 = !{i32 1, !\"dynamic_qubit_management\", i1 false}\n")
	e.writef("!3 = !{i32 1, !\"dynamic_result_management\", i1 false}\n")
}

// declareFn records an intrinsic for later declaration emission.
func (e *emitter) declareFn(intr intrinsic) {
	e.declared[intr.name] = intr
}

// gateComment returns a LLVM IR comment for the gate if comments are enabled.
func (e *emitter) gateComment(name string, qubits []int) string {
	if !e.cfg.comments {
		return ""
	}
	parts := make([]string, len(qubits))
	for i, q := range qubits {
		parts[i] = fmt.Sprintf("q[%d]", q)
	}
	return fmt.Sprintf(" ; %s %s", name, strings.Join(parts, ", "))
}

func (e *emitter) nextSSA() int {
	v := e.ssaCounter
	e.ssaCounter++
	return v
}

func (e *emitter) nextBlock(prefix string) string {
	name := fmt.Sprintf("%s_%d", prefix, e.blockCounter)
	e.blockCounter++
	return name
}

func (e *emitter) writef(format string, args ...any) {
	if e.err != nil {
		return
	}
	_, e.err = fmt.Fprintf(e.w, format, args...)
}

// qubitRef returns the QIR qubit reference for the given index.
// Qubit 0 is "ptr null", others are "ptr inttoptr (i64 N to ptr)".
func qubitRef(idx int) string {
	if idx == 0 {
		return "ptr null"
	}
	return fmt.Sprintf("ptr inttoptr (i64 %d to ptr)", idx)
}

// resultRef returns a QIR result reference for output recording.
func resultRef(idx int) string {
	if idx == 0 {
		return "ptr null"
	}
	return fmt.Sprintf("ptr inttoptr (i64 %d to ptr)", idx)
}

// resultRefWriteonly returns a QIR result reference with writeonly attribute for mz__body.
func resultRefWriteonly(idx int) string {
	if idx == 0 {
		return "ptr writeonly null"
	}
	return fmt.Sprintf("ptr writeonly inttoptr (i64 %d to ptr)", idx)
}

// resultRefReadonly returns a QIR result reference with readonly attribute for read_result.
func resultRefReadonly(idx int) string {
	if idx == 0 {
		return "ptr readonly null"
	}
	return fmt.Sprintf("ptr readonly inttoptr (i64 %d to ptr)", idx)
}

// countMeasurements counts the total number of measurement operations,
// recursing into control flow bodies.
func countMeasurements(c *ir.Circuit) int {
	count := 0
	ir.WalkOps(c.Ops(), func(op ir.Operation) {
		if op.Gate == nil && len(op.Clbits) > 0 {
			count++
		}
	})
	return count
}
